# Generated by Django 4.2.7 on 2023-11-16 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("week_commencing", models.DateField()),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("Nervous system", "Nervous system"),
                            ("First Aid", "First Aid"),
                            ("Pathology Class", "Pathology Class"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Present"),
                            (2, "Sickday"),
                            (3, "Vacation"),
                            (4, "Absent"),
                            (5, "Late"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_commencing", models.DateField()),
                (
                    "days_present",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    "days_absent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="attend.student"
                    ),
                ),
            ],
        ),
    ]
