# Generated by Django 4.2.7 on 2023-11-16 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="days_absent",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="days_present",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.DeleteModel(
            name="WeeklyAttendance",
        ),
    ]
