# Generated by Django 4.2.7 on 2023-11-16 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attend", "0002_student_days_absent_student_days_present_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="days_late",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
