# Generated by Django 4.2.7 on 2023-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attend", "0003_student_days_late"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignee", models.CharField(max_length=255)),
                ("instructor", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
