# Generated by Django 4.2.7 on 2023-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attend", "0004_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AddField(
            model_name="student",
            name="automation_button_clicked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="instructor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
